[package]
name = "torrent-prototype"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
bincode = "1"
tsyncp = { version = "0.3", features = ["bincode"] }
